### ISSUE TITLE
output.html render issue 

### ISSUE THREAD

**Issue by nd265** [UBC-MDS/census-income-prediction#13]
Hi, the output.html file in the src folder is not rendering properly and also, I guess pandas profiling won't render on github. Can we skip using it? As it is not adding any value ?

**Comment by sukhleen999** [comment]
Fair point. I'll remove it and push the updated version.

**Comment by Affrin101** [comment]
Thanks for the feedback, Sukhleen have you deleted the output.html file in ur current PR or should I delete it from github?

**Comment by sukhleen999** [comment]
I have deleted it from Github.

**Comment by Affrin101** [comment]
I am closing this issue
