### ISSUE TITLE
Color Choice for Correlation graph

### ISSUE THREAD

**Issue by PhilsChan** [UBC-MDS/census-income-prediction#21]
Which plot do you guys prefer? Should we use a diverging color scheme for the correlation graph?
I personally think the blue graph is kinda misleading and it's hard for us to distinguish the sign and magnitude of the values.
 
![Screenshot from 2021-11-21 12-48-03](https://user-images.githubusercontent.com/8486449/142778918-585843ee-5dd8-4019-aba7-ecd8fb59f254.png)
![Screenshot from 2021-11-21 12-47-23](https://user-images.githubusercontent.com/8486449/142778919-07d7d8ea-aaa9-4e68-a75b-e986aa8ec5fe.png)

**Comment by Affrin101** [comment]
Hey @PhilsChan , while the diverging scheme is the apt way to represent the correlation, in our dataset, since the correlation between the numeric columns is very little, so these graphs look pale. But, if we can add in the explanation about the pale colours then it should work fine.

**Comment by sukhleen999** [comment]
I agree with @PhilsChan , we should be using diverging color scheme for visualizing correlation. As @Affrin101 mentioned, we could add some explanation to highlight our observations.

**Comment by PhilsChan** [comment]
I have added some narrative to explain why the graph is so pale. Please check #22.

**Comment by nd265** [comment]
Yes, I think diverging color scheme would be better to visualize it as it will help us in distinguishing the correlation, but I guess there is not much correlation between the features, but diverging is better than the normal one
