### ISSUE TITLE
Test data format

### ISSUE THREAD

**Issue by PhilsChan** [UBC-MDS/census-income-prediction#28]
Hi team,
I am working on the ML pipeline, and I discovered that the test data has an extra `.` at the end of the line, making the test data have target of `<=50K.` and `>50K.` instead of `<=50K` and `>50K` in training data. 
Do you think this should be handled in `clean_data.py` or in the ML pipeline?

**Comment by nd265** [comment]
I think this can be handled while cleaning the data. I will make the changes and push my script. thanks for letting us know

**Comment by PhilsChan** [comment]
Resolved #29
