### ISSUE TITLE
ValueError: No enabled saver found that supports format='png'

### ISSUE THREAD

**Issue by sukhleen999** [UBC-MDS/census-income-prediction#37]
Hey guys, I encountered the following error while running the model_evaluation.py script:
`ValueError: No enabled saver found that supports format='png'`

If you face the same error, you can run the following command:
`$ conda install -c conda-forge altair_saver`

You can also try running `$ pip install Altair_server` before executing the above command.

**Comment by nd265** [comment]
Thanks for sharing !!
