### ISSUE TITLE
Able to create look and feel of tables by using github_document

### ISSUE THREAD

**Issue by nd265** [UBC-MDS/census-income-prediction#51]
Hi team,

I was trying to format our tables and if we do `caption = "abcd", format=markdown` then we are able to get tables like this in the `github_document`. Do you want me to go ahead and make changes for this? In this the caption will also come below the table
![image](https://user-images.githubusercontent.com/35167740/143729182-029770a4-a299-4411-a314-7b83c2297506.png)

**Comment by PhilsChan** [comment]
I think both are acceptable

**Comment by sukhleen999** [comment]
Yes, I think this is better. We can go ahead with the change.

**Comment by Affrin101** [comment]
Yes, lets go ahead with this change

**Comment by nd265** [comment]
I have added `github_document` as output but I  think html is also working fine. We can improve the look and feel in the next milestone though !!
